#!/bin/bash
source $(dirname ${BASH_SOURCE[0]})/shared-functions

# asg-functions.sh

asgs() {
  # query
  asgs=$(__read_inputs $@)
  [[ -z $asgs ]] || asgs="--auto-scaling-group-names ${asgs}"

  if [[ ! -z ${ASG_FILTERS} ]]; then
    filters="--filters ${ASG_FILTERS}"
  else
    filters=""
  fi

  aws autoscaling describe-auto-scaling-groups $filters $asgs \
    --query "AutoScalingGroups[].${ASG_OUTPUT}" \
    --output ${BMA_OUTPUT}
}

