#!/bin/bash
source $(dirname ${BASH_SOURCE[0]})/shared-functions

# asg-functions.sh

asgs() {
  # query
  asgs=$(__read_inputs $@)
  [[ -z $asgs ]] || asgs="--auto-scaling-group-names ${asgs}"

  if [[ ! -z ${ASG_FILTERS} ]]; then
    filters="--filters ${ASG_FILTERS}"
  else
    filters=""
  fi

  aws autoscaling describe-auto-scaling-groups $filters $asgs \
    --query "AutoScalingGroups[].${ASG_OUTPUT}" \
    --output ${BMA_OUTPUT}
}

asg_desired_capacity() {
  aws autoscaling describe-auto-scaling-groups      \
    --auto-scaling-group-names $(__read_inputs $@)  \
    --query 'AutoScalingGroups[].DesiredCapacity'   \
    --output ${BMA_OUTPUT}
}

asg_min_size() {
  aws autoscaling describe-auto-scaling-groups      \
    --auto-scaling-group-names $(__read_inputs $@)  \
    --query 'AutoScalingGroups[].MinSize'   \
    --output ${BMA_OUTPUT}
}

asg_max_size() {
  aws autoscaling describe-auto-scaling-groups      \
    --auto-scaling-group-names $(__read_inputs $@)  \
    --query 'AutoScalingGroups[].MaxSize'   \
    --output ${BMA_OUTPUT}
}
